export const FECTH_USER = "FECTH_USER";
export const FECTH_ALL_ARTICLES = "FECTH_ALL_ARTICLES";
export const LOAD_ARTICLE = "LOAD_ARTICLE";
export const USER_LOADING = "USER_LOADING";
export const USER_RECEIVE = "USER_RECEIVE";
export const USER_FETCH_FAIL = "USER_FETCH_FAIL";
