const BASE_URL = process.env.REACT_APP_API_BASE_URL;

const LETTERA_FRONTPAGE_URL = `${BASE_URL}/frontpage`;
const LETTERA_MOSTREAD_URL = `${BASE_URL}/mostread`;
const LETTERA_LATEST_URL = `${BASE_URL}/latest`;
const LETTERA_ARTICLE_URL = `${BASE_URL}/article`;

module.exports = {
  LETTERA_FRONTPAGE_URL,
  LETTERA_MOSTREAD_URL,
  LETTERA_LATEST_URL,
  LETTERA_ARTICLE_URL
};
